### ISSUE TITLE
Can we now remove the add-to-conf.py file and instruction in the README

### ISSUE THREAD

**Issue by ghost** [openownership/data-standard-sphinx-theme#39] opened 2018-07-11 14:55 UTC
I think not - if you do so it will use the theme installed by pip and not the local theme in /vagrant

But that means this step is only needed by people who want to actively work on the theme - so we can improve the instructions!

**Comment by stevenday** [comment] 2020-03-20 17:18
Closing as dupe of #5

**Closed as completed by stevenday** 2020-03-20 17:18 UTC
